# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 22:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PHPWalletTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='transaction amount')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='UserPHPWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0, verbose_name='Account Balance')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_wallet', to=settings.AUTH_USER_MODEL, verbose_name='Wallet Owner')),
            ],
        ),
        migrations.AddField(
            model_name='phpwallettransaction',
            name='wallet_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_from', to='wallet_core.UserPHPWallet', verbose_name='From wallet'),
        ),
        migrations.AddField(
            model_name='phpwallettransaction',
            name='wallet_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_to', to='wallet_core.UserPHPWallet', verbose_name='To Wallet'),
        ),
    ]
